name: XDD CI

on:
  push:
    branches: [ "xdd-2.0" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: apt update
      run: sudo apt-get update
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: xfsprogs gnuplot net-tools numactl libnuma-dev xfslibs-dev bc time strace
        version: 1.0
    - name: configure
      run: cmake -B ${{github.workspace}}/build
    - name: make
      run: make -C ${{github.workspace}}/build
    - name: make install
      run: sudo make -C ${{github.workspace}}/build install
    - name: run tests
      run: python ./run_tests.py
