name: XDD CI

on: [push, pull_request]

jobs:
  test:
    name: build

    runs-on: ubuntu-latest
    env:
      CFLAGS: -Wall -Wextra -Wno-unused-parameter -Werror -pedantic
    strategy:
      matrix:
        img: ["ubuntu:20.04", "ubuntu:22.04", "centos:8" ]
      fail-fast: true
    container:
      image: ${{ matrix.img }}

    steps:
    - uses: actions/checkout@v3

    - name: Ubuntu Prerequisites
      if: startsWith(matrix.img, 'ubuntu:')
      run: contrib/CI/ubuntu.sh

    - name: CentOS 8 Prerequisites
      if: matrix.img == 'centos:8'
      run: contrib/CI/centos8.sh

    - name: Configure
      run: cmake -B ${{github.workspace}}/build

    - name: Make
      run: make -C ${{github.workspace}}/build

    - name: Make Package
      run: make -C ${{github.workspace}}/build package

    - name: Install
      run: make -C ${{github.workspace}}/build install

    - name: Run Tests
      run:  |
            cd ${{github.workspace}}/build
            ctest --output-on-failure

  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt update
      run: sudo apt-get update
    - name: Install ShellCheck
      run: sudo apt -y install shellcheck
    - name: Run ShellCheck
      run: contrib/CI/shellcheck.sh .
