name: C/C++ CI

on:
  push:
    branches: [ "xdd-2.0" ]
  pull_request:
    branches: [ "xdd-2.0" ]

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt update
      run: sudo apt-get update
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: xfsprogs gnuplot net-tools numactl libnuma-dev xfslibs-dev bc time strace 
        version: 1.0
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure --prefix=$HOME/Software/xdd
    - name: make
      run: make
    - name: make install
      run: make install
  tests:
    name: tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - run: python $GITHUB_WORKSPACE/tests/run_tests.py
    

