name: C/C++ CI

on:
  push:
    branches: [ "xdd-2.0" ]
  pull_request:
    branches: [ "xdd-2.0" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: xfsprogs gnuplot net-tools numactl libnuma-dev xfslibs-dev 
        version: 1.0
    - name: autoconf
      run: autoconf
    - name: configure
      run: ./configure --prefix=$HOME/Software/xdd
    - name: make
      run: make
    - name: make check
      run: make check

